-- Add the database-row poll trigger type to launch's TriggerType enum. Without
-- it, CreateTrigger's INSERT INTO trigger (type) ... = 'database-row' is rejected
-- by Postgres (invalid enum value), the trigger silently fails to register, and
-- the dbrow poll service never sees it (GetTriggersByType returns nothing).
--
-- Pairs with api migration 131, which seeds the api-side trigger_type row. BOTH
-- are required — the api resolves trigger.type via
-- (SELECT id FROM trigger_type WHERE name = :type_name), which returns NULL and
-- violates NOT NULL without its seed, and does so SILENTLY from the operator's
-- point of view. The name must match the executor node id exactly: the api turns
-- 'trigger/database_row' into 'database-row'.
--
-- NUMBERING: golang-migrate SILENTLY SKIPS a version once a HIGHER one has been
-- applied, and a DUPLICATE version makes the service fail to boot. main is at 46
-- (46_RepairPaymentTriggerTypes) when this is written. If a concurrent branch
-- also claims 47, RENUMBER to max+1 after rebasing rather than assuming the gap
-- is free.
ALTER TYPE TriggerType ADD VALUE IF NOT EXISTS 'database-row';
