-- Add the heygen-webhook trigger type to launch's TriggerType enum. Without it,
-- CreateTrigger's INSERT INTO trigger (type) ... = 'heygen-webhook' is rejected
-- by Postgres (invalid enum value), the trigger silently fails to register, and
-- handleWebhook never routes to handleHeyGenWebhook.
--
-- Pairs with api migration 145, which seeds the api-side trigger_type row. BOTH
-- are required — the api resolves trigger.type via
-- (SELECT id FROM trigger_type WHERE name = :type_name), which returns NULL and
-- violates NOT NULL without its seed, and does so SILENTLY (flow saves 201, no
-- trigger row written, nothing logged). The name must match the executor node id
-- exactly: the api turns 'trigger/heygen_webhook' into 'heygen-webhook'
-- (underscores -> hyphens).
--
-- NUMBERING: 53. main is at 52 (52_AddApolloWebhookTriggerType) when this is
-- written. golang-migrate SILENTLY SKIPS a version once a HIGHER one has been
-- applied, and a DUPLICATE version makes the service fail to boot. If a
-- concurrent branch also claims 53, RENUMBER to max+1 after rebasing.
ALTER TYPE TriggerType ADD VALUE IF NOT EXISTS 'heygen-webhook';
